#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Vim editor
export EDITOR='vim'
export VISUAL='vim'

# Use bat for man pages
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Use starship as default prompt. Settings in ./config/starship.toml
eval "$(starship init zsh)"

# zoxide for directory jumping
eval "$(zoxide init zsh)"

# Use fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
