#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Vim editor
export EDITOR='vim'
export VISUAL='vim'

# Use bat for man pages
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Use starship as default prompt. Settings in ./config/starship.toml
eval "$(starship init zsh)"

# zoxide for directory jumping
eval "$(zoxide init zsh)"

# Use fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load custom shell functions if the file exists
if [[ -f "$HOME/.zsh_functions" ]]; then
    source "$HOME/.zsh_functions"
fi

# Load custom aliases if the file exists
# Load aliases if the file exists
if [[ -f "$HOME/.zsh_aliases" ]]; then
    source "$HOME/.zsh_aliases"
fi

# Load configuration for broot directory explorer
source "$HOME/.config/broot/launcher/bash/br"

# export paths for JAVA OPEN JDK
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export JAVA_HOME=/opt/homebrew/opt/openjdk

# >>> juliaup initialize >>>
# !! Contents within this block are managed by juliaup !!
path=('/Users/tomwright/.juliaup/bin' $path)
export PATH
# <<< juliaup initialize <<<
